// Comando para realizar um query
SELECT "CAMPOS PARA SELECIONAR" FROM "NOME DA TABELA";

// Exemplos
SELECT CPF, NOME FROM TB_CLIENTES;
SELECT ENDERECO1, ENDERECO2 AS NUMERO FROM TB_CLIENTES;
SELECT * FROM TB_CLIENTES WHERE CPF = '52400117664';
SELECT * FROM TB_CLIENTES WHERE CIDADE = 'PETROPOLIS';
SELECT * FROM TB_CLIENTES WHERE CIDADE = 'PETROPOLIS' AND BAIRRO = 'CENTRO';
SELECT * FROM TB_PRODUTOS WHERE PRECO <= 10;
SELECT * FROM TB_PRODUTOS WHERE PRECO BETWEEN 10 AND 20;