CREATE TABLE TB_CLIENTES
(
	CPF VARCHAR (11),
	NOME VARCHAR (50),
	ENDERECO1 VARCHAR (100),
	ENDERECO2 VARCHAR (100),
	BAIRRO VARCHAR (50),
	CIDADE VARCHAR (50),
	ESTADO VARCHAR (2),
	CEP VARCHAR (8),
	IDADE INT,
	SEXO VARCHAR(1),
	LIMITE_CREDITO DOUBLE,
	VOLUME_COMPRA FLOAT,
	PRIMEIRA_COMPRA BIT (1)
);